Name:           ros-jade-webtest
Version:        2.0.18
Release:        0%{?dist}
Summary:        ROS webtest package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       python-beautifulsoup4
Requires:       python-six
Requires:       python-waitress >= 0.8.5
Requires:       python-webob >= 1.2
BuildRequires:  python-beautifulsoup4
BuildRequires:  python-mock
BuildRequires:  python-nose
BuildRequires:  python-paste-deploy
BuildRequires:  python-pyquery
BuildRequires:  python-six
BuildRequires:  python-waitress >= 0.8.5
BuildRequires:  python-webob >= 1.2
BuildRequires:  ros-jade-catkin >= 0.6.18
BuildRequires:  ros-jade-catkin-pip >= 0.1.3

%description
Configuration package for Pyros

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Sep 05 2016 AlexV <asmodehn@gmail.com> - 2.0.18-0
- Autogenerated by Bloom

